// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Teachy.Data;

#nullable disable

namespace Teachy.Migrations
{
    [DbContext(typeof(TeachyDbContext))]
    [Migration("20220624151822_AddsTags")]
    partial class AddsTags
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Teachy.Data.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CountryOfOriginId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("Date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CountryOfOriginId");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("Teachy.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Teachy.Data.Models.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("InviteCode")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("Teachy.Data.Models.ClassMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("integer");

                    b.Property<int>("MemberId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("MemberId");

                    b.ToTable("ClassMembers");
                });

            modelBuilder.Entity("Teachy.Data.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Albania"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Austria"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Bahrain"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Belize"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Bhutan"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Bosnia & Herzegovina"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Brunei"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Chile"
                        },
                        new
                        {
                            Id = 24,
                            Name = "China"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Congo - Kinshasa"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Côte d’Ivoire"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Czechia"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = 36,
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Faroe Islands"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Finland"
                        },
                        new
                        {
                            Id = 42,
                            Name = "France"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Greece"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Greenland"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Hong Kong SAR China"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = 53,
                            Name = "India"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Iran"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Israel"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Japan"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Laos"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Latin America"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Lebanon"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Libya"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Mali"
                        },
                        new
                        {
                            Id = 77,
                            Name = "Malta"
                        },
                        new
                        {
                            Id = 78,
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Moldova"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Myanmar (Burma)"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = 86,
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = 87,
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = 89,
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = 90,
                            Name = "North Macedonia"
                        },
                        new
                        {
                            Id = 91,
                            Name = "Norway"
                        },
                        new
                        {
                            Id = 92,
                            Name = "Oman"
                        },
                        new
                        {
                            Id = 93,
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = 94,
                            Name = "Panama"
                        },
                        new
                        {
                            Id = 95,
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = 96,
                            Name = "Peru"
                        },
                        new
                        {
                            Id = 97,
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = 98,
                            Name = "Poland"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 100,
                            Name = "Puerto Rico"
                        },
                        new
                        {
                            Id = 101,
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = 102,
                            Name = "Réunion"
                        },
                        new
                        {
                            Id = 103,
                            Name = "Romania"
                        },
                        new
                        {
                            Id = 104,
                            Name = "Russia"
                        },
                        new
                        {
                            Id = 105,
                            Name = "Rwanda"
                        },
                        new
                        {
                            Id = 106,
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = 107,
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = 108,
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = 109,
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = 110,
                            Name = "Slovakia"
                        },
                        new
                        {
                            Id = 111,
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = 112,
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = 113,
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = 114,
                            Name = "South Korea"
                        },
                        new
                        {
                            Id = 115,
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 116,
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = 117,
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = 118,
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = 119,
                            Name = "Syria"
                        },
                        new
                        {
                            Id = 120,
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = 121,
                            Name = "Trinidad & Tobago"
                        },
                        new
                        {
                            Id = 122,
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = 123,
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = 124,
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Id = 125,
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 126,
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = 127,
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = 128,
                            Name = "United States"
                        },
                        new
                        {
                            Id = 129,
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = 130,
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = 131,
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = 132,
                            Name = "Vietnam"
                        },
                        new
                        {
                            Id = 133,
                            Name = "World"
                        },
                        new
                        {
                            Id = 134,
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = 135,
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("Teachy.Data.Models.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<byte[]>("FileContent")
                        .HasColumnType("bytea");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ResourceTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Uri")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ResourceTypeId");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("Teachy.Data.Models.ResourceTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ResourceId")
                        .HasColumnType("integer");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.HasIndex("TagId");

                    b.ToTable("ResourceTags");
                });

            modelBuilder.Entity("Teachy.Data.Models.ResourceType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ResourceType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Uri"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Document"
                        });
                });

            modelBuilder.Entity("Teachy.Data.Models.SubCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name", "CategoryId")
                        .IsUnique();

                    b.ToTable("SubCategories");
                });

            modelBuilder.Entity("Teachy.Data.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Teachy.Data.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Auth0Id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("Teachy.Data.Models.Author", b =>
                {
                    b.HasOne("Teachy.Data.Models.Country", "CountryOfOrigin")
                        .WithMany()
                        .HasForeignKey("CountryOfOriginId");

                    b.Navigation("CountryOfOrigin");
                });

            modelBuilder.Entity("Teachy.Data.Models.Class", b =>
                {
                    b.HasOne("Teachy.Data.Models.UserProfile", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Teachy.Data.Models.ClassMember", b =>
                {
                    b.HasOne("Teachy.Data.Models.Class", "Class")
                        .WithMany("ClassMembers")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Teachy.Data.Models.UserProfile", "Member")
                        .WithMany("ClassMembers")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Teachy.Data.Models.Resource", b =>
                {
                    b.HasOne("Teachy.Data.Models.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Teachy.Data.Models.ResourceType", "ResourceType")
                        .WithMany()
                        .HasForeignKey("ResourceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Teachy.Data.Models.SubCategory", "SubCategory")
                        .WithMany()
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("ResourceType");

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("Teachy.Data.Models.ResourceTag", b =>
                {
                    b.HasOne("Teachy.Data.Models.Resource", "Resource")
                        .WithMany("ResourceTags")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Teachy.Data.Models.Tag", "Tag")
                        .WithMany("ResourceTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Teachy.Data.Models.SubCategory", b =>
                {
                    b.HasOne("Teachy.Data.Models.Category", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Teachy.Data.Models.Category", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("Teachy.Data.Models.Class", b =>
                {
                    b.Navigation("ClassMembers");
                });

            modelBuilder.Entity("Teachy.Data.Models.Resource", b =>
                {
                    b.Navigation("ResourceTags");
                });

            modelBuilder.Entity("Teachy.Data.Models.Tag", b =>
                {
                    b.Navigation("ResourceTags");
                });

            modelBuilder.Entity("Teachy.Data.Models.UserProfile", b =>
                {
                    b.Navigation("ClassMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
